### PR TITLE
fix: fixed defect with multiline tfvars not being escaped

### LINKED ISSUE #630: otf generated tfvars files don't support multiline strings
Variable set's of type terraform don't currently support multiline strings. This is because the code that generates the tfvars file serializes variables to the file via the following snippet.

```golang
b.WriteString(`"`)
b.WriteString(v.Value)
b.WriteString(`"`)
```

A simple solution might be to use the heredoc encoding to handle this. I checked in the upstream hashicorp terraform code, and didn't see any escape method that we could easily leverage here.

### PR DESCRIPTION
**Pull request by robbert229**
This PR resolves #630 by using heredocs in variables when that variable includes a newline. 

This PR isn't intended to fix all escaping with the WriteTerraformVars function, and there are other ways that this can be broken (for example using backspaces and double quotes within the value of the variable)

### CODE REVIEW

File: internal/variable/variable.go [hunk 1]
```diff
@@ -281,6 +281,15 @@ func WriteTerraformVars(dir string, vars []*Variable) error {
 			b.WriteString(" = ")
 			if v.HCL {
 				b.WriteString(v.Value)
```
Comment (robbert229) [inline internal/variable/variable.go:283]: Here we are using EOT as the base delimiter for the heredoc, and optionally adding extra Ts to it if the delimiter is already contained by the value.

**Comment by leg100** [comment]
Thanks! Good point re double quotes, backspaces, etc. We'll tackle those another day.
